[project]
name = "crewai-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "crewai-tools>=1.9.3",
    "crewai[google-genai,tool]>=1.9.3",
    "google-search-results>=2.4.2",
]
